name: Sync to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: pip install git-filter-repo

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hfspace https://RohitMugalya:$HF_TOKEN@huggingface.co/spaces/RohitMugalya/zero-shot-video-classifier
          git filter-repo --path assets/images --invert-paths --force
          git push hfspace main --force